config = {'input_length': 3,
          'num_time_steps': 50,
          'batch_size': 50,
          'train_ratio': 0.9,
          'lstm_size': 250,
          'num_lstm_cells': 3,
          'dropout_prob': 0.5,
          'reg_strength': 1e-3,
          'initial_learning_rate': 5e-3,
          'num_epochs_before_decay': 2,
          'decay_rate': 0.7,
          'num_epochs': 30,
          'test_model_every': 1,
          'log_dir': "log",
          'model_name': "checkpoint_00"
         }